version: '3'
services:

  api:
    build: ./api
    # Mapping ports -> CONTAINER:HOST
    ports:
      - "8080-8081:8080"
    environment:
      - "JAVA_OPTS=-Ddebug -Xmx128m"
    networks:
      - front-back
      
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - front-back
    volumes:
      - ./frontend/nginx/certs/:/etc/nginx/ssl

networks:
  front-back:
    driver: bridge